### ISSUE TITLE
[Suggestion] Use .vscode extensions.json

### ISSUE THREAD

**Issue by BenShelton** [Grey41/JS-ByteBase#2]
https://github.com/Grey41/JS-ByteBase/blob/726816a7daa74a42bea87adb6e38309120c47ac5/README.md?plain=1#L8-L10

Instead of recommending extensions in the readme, you can use a file in `.vscode/extensions.json` which will automatically prompt the user when they open the project to install the extensions.

See https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions for more details.

**Comment by Grey41** [comment]
Thanks for the suggestion. View the file [extensions.json here](https://github.com/Grey41/JS-ByteBase/blob/master/.vscode/extensions.json).
