### ISSUE TITLE
[Bug] Search does nothing

### ISSUE THREAD

**Issue by BenShelton** [Grey41/JS-ByteBase#6]
It doesn't matter what is typed into the search, results aren't filtered.

**Comment by Grey41** [comment]
The JS-ByteBase search feature isn't meant to filter the results. When you type something into the search bar, the server rates each project based on matches in its title, tags, description and comments. The most relevant projects come up first and they get less and less relevant as you scroll down the page. This will be noticeable when more projects have been posted.

**Comment by BenShelton** [comment]
I would argue that if a project has 0 relevance (as in nothing matches at all) that it shouldn't be included. If no results are found instead a "No results found" kind of message would appear. That's a much more familiar experience that most websites use. YouTube for example doesn't return every video ever no matter what you search for.

**Comment by Grey41** [comment]
Your point has been reconsidered. I agree, it would be annoying if you searched absolute nonsense and it still provided a list of results.
